version: '3'

services:
  backend:
    build: .
    command: >
      sh -c "python3 manage.py collectstatic --noinput &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    environment:
      POSTGRES_DB: 'blog'
      POSTGRES_USER: 'blog_user'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: 'postgres:14.0'
    environment:
      POSTGRES_DB: 'blog'
      POSTGRES_USER: 'blog_user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - "5432:5432"
